apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: nginx-private
    nginx.ingress.kubernetes.io/service-upstream: "{{ .Values.ingress.serviceUpstream | default false }}"
  labels:
    app/name: {{ $.Chart.Name }}
    app/instance: {{ $.Release.Name }}
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  rules:
    - host: {{ $.Values.ingress.host }}
      http:
        paths:
          - path: /api(/|$)(.*)
            backend:
              serviceName: {{ $.Release.Name }}
              servicePort: 80