<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.10.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="3.1.0" />
    <PackageReference Include="prometheus-net" Version="8.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Common.Contracts\Common.Contracts.csproj" />
    <ProjectReference Include="..\..\Contracts\Order.Contracts\OrderProcessing.Contracts.csproj" />
    <ProjectReference Include="..\..\Domain\Order.Domain\OrderProcessing.Domain.csproj" />
  </ItemGroup>

</Project>
