services:

services:
  order-api:
    build: ./src/OrderApi
    ports:
      - "5000:80"
    environment:
      Kafka__BootstrapServers: kafka:9092

  order-processor:
    build: ./src/OrderProcessor
    environment:
      Kafka__BootstrapServers: kafka:9092
    depends_on:
      - kafka


  # external-api:
  #   build:
  #     context: .
  #     dockerfile: src/ExternalServices/Hosts/External.Api/Dockerfile
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
  #   depends_on:
  #     kafka:
  #       condition: service_started
  
  # order-api:
  #   build:
  #     context: .
  #     dockerfile: src/OrderServices/Hosts/Order.Api/Dockerfile
  #   ports:
  #     - "5001:80"
  #   environment:
  #     - CASSANDRA_CONTACT_POINTS=cassandra
  #     - CASSANDRA_PORT=9042
  #   depends_on:
  #     cassandra:
  #       condition: service_healthy
  #     kafka:
  #       condition: service_started

  # order-daemon:
  #   build:
  #     context: .
  #     dockerfile: src/OrderServices/Hosts/Order.Daemon/Dockerfile
  #   environment:
  #     - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
  #     - ORDER_API_URL=http://orderapi
  #   depends_on:
  #     order-api:
  #       condition: service_started
  #     kafka:
  #       condition: service_started