apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Release"
            - name: "ASPNETCORE_DOCKERIZED"
              value: "1"
            - name: ASPNETCORE_URLS
              value: http://*:8080
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: settings
              mountPath: /app/appsettings.json
              subPath: appsettings.json
            - name: settings
              mountPath: /app/appsettings.Release.json
              subPath: appsettings.Release.json
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      volumes:
        - name: settings
          configMap:
            name: "{{ .Release.Name }}"