apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations:
  {{- if .Values.rtsClusters.service.global }}
    io.cilium/global-service: "true"
    io.cilium/service-affinity: {{ .Values..service.affinity }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}
