apiVersion: v1
name: crypto-exchange-api
description: API 
type: application

# Версия чарта
# Фактическая версия подставляется при деплое
version: 0.1.0

# Версия приложения
# Фактическая версия подставляется при деплое
appVersion: 1.2.0
